### ISSUE TITLE
Allow use of parens and brackets in haml content

### ISSUE THREAD

**Issue by davidstump** [nurugger07/calliope#26]
First - love the library. Had a lot of fun playing with it this evening :)

I was playing with Angular and was running into some issues with the paren and bracket characters being picked up as attributes every time they appear in a line. A few examples:
```
%h1 {{user.name}}
```
would ideally parse to 
```
<h1>{{user.name}}</h1>
```
and
```
%a{ng-click: "doSomething()"} Click Me
```
would parse to 
```
<a ng-click="doSomething()"> Click Me </a>
```

In both of those cases I believe the ( or { character is being picked up by the parser as an indicator of an attribute on the element itself versus html content. I tried to glance at the parser to see if it was a reasonably easy fix to submit a PR, but without a lot of time tonight and being brand new to Elixir I didn't have much luck. 

Thanks for the awesome work!

**Comment by YellowApple** [comment]
Stopping by to mention that I'm still running into this issue with Calliope 0.3.0 (the latest, as far as I can tell).  So, something like `%h1 (foo)` gets rendered as `<h1 "foo">` instead of the expected `<h1>(foo)</h1>`.  Looks as if `Calliope.Parser.parse_line/2` is matching on `@parens` and `@attrs` without taking into account whether a HAML tag immediately precedes them.  Should I open a new issue for this, seeing as this one is both closed and more than a year and a half old?
